; ========= Measures =========

[MeasureInputTextCpu0]
Measure=Plugin
Plugin=InputText
FontColor=#colorMain#
SolidColor=#colorHwinfoBackground#
FontSize=8
FontFace=Roboto Cn
FocusDismiss=1
UpdateDivider=-1
Antialias=1
Command1=[!WriteKeyValue Variables HWiNFO-CPU0-SensorId "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-SensorId# X=[Cpu0SensorIdInputString:X] Y=[Cpu0SensorIdInputString:Y] W=[Cpu0SensorIdInputString:W] H=[Cpu0SensorIdInputString:H]
Command2=[!WriteKeyValue Variables HWiNFO-CPU0-SensorInstance "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-SensorInstance# X=[Cpu0SensorInstanceInputString:X] Y=[Cpu0SensorInstanceInputString:Y] W=[Cpu0SensorInstanceInputString:W] H=[Cpu0SensorInstanceInputString:H]
Command3=[!WriteKeyValue Variables HWiNFO-CPU0-Core0Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core0Clock# X=[Cpu0Core0ClockInputString:X] Y=[Cpu0Core0ClockInputString:Y] W=[Cpu0Core0ClockInputString:W] H=[Cpu0Core0ClockInputString:H]
Command4=[!WriteKeyValue Variables HWiNFO-CPU0-Core1Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core1Clock# X=[Cpu0Core1ClockInputString:X] Y=[Cpu0Core1ClockInputString:Y] W=[Cpu0Core1ClockInputString:W] H=[Cpu0Core1ClockInputString:H]
Command5=[!WriteKeyValue Variables HWiNFO-CPU0-Core2Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core2Clock# X=[Cpu0Core2ClockInputString:X] Y=[Cpu0Core2ClockInputString:Y] W=[Cpu0Core2ClockInputString:W] H=[Cpu0Core2ClockInputString:H]
Command6=[!WriteKeyValue Variables HWiNFO-CPU0-Core3Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core3Clock# X=[Cpu0Core3ClockInputString:X] Y=[Cpu0Core3ClockInputString:Y] W=[Cpu0Core3ClockInputString:W] H=[Cpu0Core3ClockInputString:H]
Command7=[!WriteKeyValue Variables HWiNFO-CPU0-Core4Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core4Clock# X=[Cpu0Core4ClockInputString:X] Y=[Cpu0Core4ClockInputString:Y] W=[Cpu0Core4ClockInputString:W] H=[Cpu0Core4ClockInputString:H]
Command8=[!WriteKeyValue Variables HWiNFO-CPU0-Core5Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core5Clock# X=[Cpu0Core5ClockInputString:X] Y=[Cpu0Core5ClockInputString:Y] W=[Cpu0Core5ClockInputString:W] H=[Cpu0Core5ClockInputString:H]
Command9=[!WriteKeyValue Variables HWiNFO-CPU0-Core6Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core6Clock# X=[Cpu0Core6ClockInputString:X] Y=[Cpu0Core6ClockInputString:Y] W=[Cpu0Core6ClockInputString:W] H=[Cpu0Core6ClockInputString:H]
Command10=[!WriteKeyValue Variables HWiNFO-CPU0-Core7Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core7Clock# X=[Cpu0Core7ClockInputString:X] Y=[Cpu0Core7ClockInputString:Y] W=[Cpu0Core7ClockInputString:W] H=[Cpu0Core7ClockInputString:H]
Command11=[!WriteKeyValue Variables HWiNFO-CPU0-Core8Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core8Clock# X=[Cpu0Core8ClockInputString:X] Y=[Cpu0Core8ClockInputString:Y] W=[Cpu0Core8ClockInputString:W] H=[Cpu0Core8ClockInputString:H]
Command12=[!WriteKeyValue Variables HWiNFO-CPU0-Core9Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core9Clock# X=[Cpu0Core9ClockInputString:X] Y=[Cpu0Core9ClockInputString:Y] W=[Cpu0Core9ClockInputString:W] H=[Cpu0Core9ClockInputString:H]
Command13=[!WriteKeyValue Variables HWiNFO-CPU0-Core10Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core10Clock# X=[Cpu0Core10ClockInputString:X] Y=[Cpu0Core10ClockInputString:Y] W=[Cpu0Core10ClockInputString:W] H=[Cpu0Core10ClockInputString:H]
Command14=[!WriteKeyValue Variables HWiNFO-CPU0-Core11Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core11Clock# X=[Cpu0Core11ClockInputString:X] Y=[Cpu0Core11ClockInputString:Y] W=[Cpu0Core11ClockInputString:W] H=[Cpu0Core11ClockInputString:H]
Command15=[!WriteKeyValue Variables HWiNFO-CPU0-Core12Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core12Clock# X=[Cpu0Core12ClockInputString:X] Y=[Cpu0Core12ClockInputString:Y] W=[Cpu0Core12ClockInputString:W] H=[Cpu0Core12ClockInputString:H]
Command16=[!WriteKeyValue Variables HWiNFO-CPU0-Core13Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core13Clock# X=[Cpu0Core13ClockInputString:X] Y=[Cpu0Core13ClockInputString:Y] W=[Cpu0Core13ClockInputString:W] H=[Cpu0Core13ClockInputString:H]
Command17=[!WriteKeyValue Variables HWiNFO-CPU0-Core14Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core14Clock# X=[Cpu0Core14ClockInputString:X] Y=[Cpu0Core14ClockInputString:Y] W=[Cpu0Core14ClockInputString:W] H=[Cpu0Core14ClockInputString:H]
Command18=[!WriteKeyValue Variables HWiNFO-CPU0-Core15Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core15Clock# X=[Cpu0Core15ClockInputString:X] Y=[Cpu0Core15ClockInputString:Y] W=[Cpu0Core15ClockInputString:W] H=[Cpu0Core15ClockInputString:H]
Command19=[!WriteKeyValue Variables HWiNFO-CPU0-Core0VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core0VID# X=[Cpu0Core0VIDInputString:X] Y=[Cpu0Core0VIDInputString:Y] W=[Cpu0Core0VIDInputString:W] H=[Cpu0Core0VIDInputString:H]
Command20=[!WriteKeyValue Variables HWiNFO-CPU0-Core1VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core1VID# X=[Cpu0Core1VIDInputString:X] Y=[Cpu0Core1VIDInputString:Y] W=[Cpu0Core1VIDInputString:W] H=[Cpu0Core1VIDInputString:H]
Command21=[!WriteKeyValue Variables HWiNFO-CPU0-Core2VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core2VID# X=[Cpu0Core2VIDInputString:X] Y=[Cpu0Core2VIDInputString:Y] W=[Cpu0Core2VIDInputString:W] H=[Cpu0Core2VIDInputString:H]
Command22=[!WriteKeyValue Variables HWiNFO-CPU0-Core3VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core3VID# X=[Cpu0Core3VIDInputString:X] Y=[Cpu0Core3VIDInputString:Y] W=[Cpu0Core3VIDInputString:W] H=[Cpu0Core3VIDInputString:H]
Command23=[!WriteKeyValue Variables HWiNFO-CPU0-Core4VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core4VID# X=[Cpu0Core4VIDInputString:X] Y=[Cpu0Core4VIDInputString:Y] W=[Cpu0Core4VIDInputString:W] H=[Cpu0Core4VIDInputString:H]
Command24=[!WriteKeyValue Variables HWiNFO-CPU0-Core5VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core5VID# X=[Cpu0Core5VIDInputString:X] Y=[Cpu0Core5VIDInputString:Y] W=[Cpu0Core5VIDInputString:W] H=[Cpu0Core5VIDInputString:H]
Command25=[!WriteKeyValue Variables HWiNFO-CPU0-Core6VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core6VID# X=[Cpu0Core6VIDInputString:X] Y=[Cpu0Core6VIDInputString:Y] W=[Cpu0Core6VIDInputString:W] H=[Cpu0Core6VIDInputString:H]
Command26=[!WriteKeyValue Variables HWiNFO-CPU0-Core7VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core7VID# X=[Cpu0Core7VIDInputString:X] Y=[Cpu0Core7VIDInputString:Y] W=[Cpu0Core7VIDInputString:W] H=[Cpu0Core7VIDInputString:H]
Command27=[!WriteKeyValue Variables HWiNFO-CPU0-Core8VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core8VID# X=[Cpu0Core8VIDInputString:X] Y=[Cpu0Core8VIDInputString:Y] W=[Cpu0Core8VIDInputString:W] H=[Cpu0Core8VIDInputString:H]
Command28=[!WriteKeyValue Variables HWiNFO-CPU0-Core9VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core9VID# X=[Cpu0Core9VIDInputString:X] Y=[Cpu0Core9VIDInputString:Y] W=[Cpu0Core9VIDInputString:W] H=[Cpu0Core9VIDInputString:H]
Command29=[!WriteKeyValue Variables HWiNFO-CPU0-Core10VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core10VID# X=[Cpu0Core10VIDInputString:X] Y=[Cpu0Core10VIDInputString:Y] W=[Cpu0Core10VIDInputString:W] H=[Cpu0Core10VIDInputString:H]
Command30=[!WriteKeyValue Variables HWiNFO-CPU0-Core11VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core11VID# X=[Cpu0Core11VIDInputString:X] Y=[Cpu0Core11VIDInputString:Y] W=[Cpu0Core11VIDInputString:W] H=[Cpu0Core11VIDInputString:H]
Command31=[!WriteKeyValue Variables HWiNFO-CPU0-Core12VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core12VID# X=[Cpu0Core12VIDInputString:X] Y=[Cpu0Core12VIDInputString:Y] W=[Cpu0Core12VIDInputString:W] H=[Cpu0Core12VIDInputString:H]
Command32=[!WriteKeyValue Variables HWiNFO-CPU0-Core13VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core13VID# X=[Cpu0Core13VIDInputString:X] Y=[Cpu0Core13VIDInputString:Y] W=[Cpu0Core13VIDInputString:W] H=[Cpu0Core13VIDInputString:H]
Command33=[!WriteKeyValue Variables HWiNFO-CPU0-Core14VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core14VID# X=[Cpu0Core14VIDInputString:X] Y=[Cpu0Core14VIDInputString:Y] W=[Cpu0Core14VIDInputString:W] H=[Cpu0Core14VIDInputString:H]
Command34=[!WriteKeyValue Variables HWiNFO-CPU0-Core15VID "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-Core15VID# X=[Cpu0Core15VIDInputString:X] Y=[Cpu0Core15VIDInputString:Y] W=[Cpu0Core15VIDInputString:W] H=[Cpu0Core15VIDInputString:H]
DynamicVariables=1

[MeasureInputTextCpu0Dts]
Measure=Plugin
Plugin=InputText
FontColor=#colorMain#
SolidColor=#colorHwinfoBackground#
FontSize=8
FontFace=Roboto Cn
FocusDismiss=1
UpdateDivider=-1
Antialias=1
Command1=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-SensorId "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-SensorId# X=[Cpu0DtsSensorIdInputString:X] Y=[Cpu0DtsSensorIdInputString:Y] W=[Cpu0DtsSensorIdInputString:W] H=[Cpu0DtsSensorIdInputString:H]
Command2=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-SensorInstance "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-SensorInstance# X=[Cpu0DtsSensorInstanceInputString:X] Y=[Cpu0DtsSensorInstanceInputString:Y] W=[Cpu0DtsSensorInstanceInputString:W] H=[Cpu0DtsSensorInstanceInputString:H]
Command3=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core0Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core0Temp# X=[Cpu0DtsCore0TempInputString:X] Y=[Cpu0DtsCore0TempInputString:Y] W=[Cpu0DtsCore0TempInputString:W] H=[Cpu0DtsCore0TempInputString:H]
Command4=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core1Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core1Temp# X=[Cpu0DtsCore1TempInputString:X] Y=[Cpu0DtsCore1TempInputString:Y] W=[Cpu0DtsCore1TempInputString:W] H=[Cpu0DtsCore1TempInputString:H]
Command5=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core2Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core2Temp# X=[Cpu0DtsCore2TempInputString:X] Y=[Cpu0DtsCore2TempInputString:Y] W=[Cpu0DtsCore2TempInputString:W] H=[Cpu0DtsCore2TempInputString:H]
Command6=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core3Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core3Temp# X=[Cpu0DtsCore3TempInputString:X] Y=[Cpu0DtsCore3TempInputString:Y] W=[Cpu0DtsCore3TempInputString:W] H=[Cpu0DtsCore3TempInputString:H]
Command7=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core4Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core4Temp# X=[Cpu0DtsCore4TempInputString:X] Y=[Cpu0DtsCore4TempInputString:Y] W=[Cpu0DtsCore4TempInputString:W] H=[Cpu0DtsCore4TempInputString:H]
Command8=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core5Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core5Temp# X=[Cpu0DtsCore5TempInputString:X] Y=[Cpu0DtsCore5TempInputString:Y] W=[Cpu0DtsCore5TempInputString:W] H=[Cpu0DtsCore5TempInputString:H]
Command9=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core6Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core6Temp# X=[Cpu0DtsCore6TempInputString:X] Y=[Cpu0DtsCore6TempInputString:Y] W=[Cpu0DtsCore6TempInputString:W] H=[Cpu0DtsCore6TempInputString:H]
Command10=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core7Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core7Temp# X=[Cpu0DtsCore7TempInputString:X] Y=[Cpu0DtsCore7TempInputString:Y] W=[Cpu0DtsCore7TempInputString:W] H=[Cpu0DtsCore7TempInputString:H]
Command11=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core8Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core8Temp# X=[Cpu0DtsCore8TempInputString:X] Y=[Cpu0DtsCore8TempInputString:Y] W=[Cpu0DtsCore8TempInputString:W] H=[Cpu0DtsCore8TempInputString:H]
Command12=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core9Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core9Temp# X=[Cpu0DtsCore9TempInputString:X] Y=[Cpu0DtsCore9TempInputString:Y] W=[Cpu0DtsCore9TempInputString:W] H=[Cpu0DtsCore9TempInputString:H]
Command13=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core10Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core10Temp# X=[Cpu0DtsCore10TempInputString:X] Y=[Cpu0DtsCore10TempInputString:Y] W=[Cpu0DtsCore10TempInputString:W] H=[Cpu0DtsCore10TempInputString:H]
Command14=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core11Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core11Temp# X=[Cpu0DtsCore11TempInputString:X] Y=[Cpu0DtsCore11TempInputString:Y] W=[Cpu0DtsCore11TempInputString:W] H=[Cpu0DtsCore11TempInputString:H]
Command15=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core12Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core12Temp# X=[Cpu0DtsCore12TempInputString:X] Y=[Cpu0DtsCore12TempInputString:Y] W=[Cpu0DtsCore12TempInputString:W] H=[Cpu0DtsCore12TempInputString:H]
Command16=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core13Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core13Temp# X=[Cpu0DtsCore13TempInputString:X] Y=[Cpu0DtsCore13TempInputString:Y] W=[Cpu0DtsCore13TempInputString:W] H=[Cpu0DtsCore13TempInputString:H]
Command17=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core14Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core14Temp# X=[Cpu0DtsCore14TempInputString:X] Y=[Cpu0DtsCore14TempInputString:Y] W=[Cpu0DtsCore14TempInputString:W] H=[Cpu0DtsCore14TempInputString:H]
Command18=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-Core15Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-Core15Temp# X=[Cpu0DtsCore15TempInputString:X] Y=[Cpu0DtsCore15TempInputString:Y] W=[Cpu0DtsCore15TempInputString:W] H=[Cpu0DtsCore15TempInputString:H]
Command19=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-PackageTemp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-PackageTemp# X=[Cpu0DtsPackageTempInputString:X] Y=[Cpu0DtsPackageTempInputString:Y] W=[Cpu0DtsPackageTempInputString:W] H=[Cpu0DtsPackageTempInputString:H]
Command20=[!WriteKeyValue Variables HWiNFO-CPU0-DTS-PackageTt "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-CPU0-DTS-PackageTt# X=[Cpu0DtsThermalThrottlingInputString:X] Y=[Cpu0DtsThermalThrottlingInputString:Y] W=[Cpu0DtsThermalThrottlingInputString:W] H=[Cpu0DtsThermalThrottlingInputString:H]

[MeasureInputTextMobo]
Measure=Plugin
Plugin=InputText
FontColor=#colorMain#
SolidColor=#colorHwinfoBackground#
FontSize=8
FontFace=Roboto Cn
FocusDismiss=1
UpdateDivider=-1
Antialias=1
Command1=[!WriteKeyValue Variables HWiNFO-MOBO-SensorId "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-MOBO-SensorId# X=[MoboSensorIdInputString:X] Y=[MoboSensorIdInputString:Y] W=[MoboSensorIdInputString:W] H=[MoboSensorIdInputString:H]
Command2=[!WriteKeyValue Variables HWiNFO-MOBO-SensorInstance "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-MOBO-SensorInstance# X=[MoboSensorInstanceInputString:X] Y=[MoboSensorInstanceInputString:Y] W=[MoboSensorInstanceInputString:W] H=[MoboSensorInstanceInputString:H]
Command3=[!WriteKeyValue Variables HWiNFO-MOBO-CpuFan "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-MOBO-CpuFan# X=[MoboCpuFanInputString:X] Y=[MoboCpuFanInputString:Y] W=[MoboCpuFanInputString:W] H=[MoboCpuFanInputString:H]

; ========= Meters =========

[Cpu0LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoSectionLabel
Text="CPU0 / CPU0:DTS"

[Cpu0ClockSpeedsLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
StringAlign=Left
X=(#hwinfoColumnX# + 7)
Text="Clock Speed"

[Cpu0SensorIdLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor ID"

[Cpu0SensorInstanceLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor Instance"

[Cpu0Core0LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 0"

[Cpu0Core1LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 1"

[Cpu0Core2LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 2"

[Cpu0Core3LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 3"

[Cpu0Core4LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 4"

[Cpu0Core5LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 5"

[Cpu0Core6LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 6"

[Cpu0Core7LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 7"

[Cpu0Core8LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 8"

[Cpu0Core9LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 9"

[Cpu0Core10LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 10"

[Cpu0Core11LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 11"

[Cpu0Core12LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 12"

[Cpu0Core13LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 13"

[Cpu0Core14LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 14"

[Cpu0Core15LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core 15"

[Cpu0SensorIdInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
X=(#hwinfoColumnX# + 1)
Y=[Cpu0SensorIdLabelString:Y]
Text="#HWiNFO-CPU0-SensorId#"
DynamicVariables=1
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 1"]

[Cpu0SensorInstanceInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-SensorInstance#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 2"]

[Cpu0Core0ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core0Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 3"]

[Cpu0Core1ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core1Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 4"]

[Cpu0Core2ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core2Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 5"]

[Cpu0Core3ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core3Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 6"]

[Cpu0Core4ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core4Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 7"]

[Cpu0Core5ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core5Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 8"]

[Cpu0Core6ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core6Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 9"]

[Cpu0Core7ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core7Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 10"]

[Cpu0Core8ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core8Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 11"]

[Cpu0Core9ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core9Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 12"]

[Cpu0Core10ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core10Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 13"]

[Cpu0Core11ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core11Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 14"]

[Cpu0Core12ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core12Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 15"]

[Cpu0Core13ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core13Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 16"]

[Cpu0Core14ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core14Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 17"]

[Cpu0Core15ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core15Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 18"]

[Cpu0VIDLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
StringAlign=Left
X=9R
Y=[Cpu0ClockSpeedsLabelString:Y]
Text="Voltage (VID)"
DynamicVariables=1

[Cpu0VIDSensorIdString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
FontColor=#colorInfo#
X=-6r
Y=[Cpu0SensorIdInputString:Y]
Text="#HWiNFO-CPU0-SensorId#"
DynamicVariables=1

[Cpu0VIDSensorInstanceString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
FontColor=#colorInfo#
Text="#HWiNFO-CPU0-SensorInstance#"

[Cpu0Core0VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core0VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 19"]

[Cpu0Core1VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core1VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 20"]

[Cpu0Core2VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core2VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 21"]

[Cpu0Core3VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core3VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 22"]

[Cpu0Core4VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core4VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 23"]

[Cpu0Core5VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core5VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 24"]

[Cpu0Core6VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core6VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 25"]

[Cpu0Core7VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core7VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 26"]

[Cpu0Core8VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core8VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 27"]

[Cpu0Core9VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core9VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 28"]

[Cpu0Core10VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core10VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 29"]

[Cpu0Core11VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core11VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 30"]

[Cpu0Core12VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core12VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 31"]

[Cpu0Core13VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core13VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 32"]

[Cpu0Core14VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core14VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 33"]

[Cpu0Core15VIDInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-Core15VID#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0 "Executebatch 34"]

[Cpu0DtsTempLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
StringAlign=Left
X=9R
Y=[Cpu0ClockSpeedsLabelString:Y]
Text="Temperature"
DynamicVariables=1

[Cpu0DtsSensorIdInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
X=-6r
Y=[Cpu0SensorIdLabelString:Y]
Text="#HWiNFO-CPU0-DTS-SensorId#"
DynamicVariables=1
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 1"]

[Cpu0DtsSensorInstanceInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-SensorInstance#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 2"]

[Cpu0DtsCore0TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core0Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 3"]

[Cpu0DtsCore1TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core1Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 4"]

[Cpu0DtsCore2TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core2Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 5"]

[Cpu0DtsCore3TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core3Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 6"]

[Cpu0DtsCore4TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core4Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 7"]

[Cpu0DtsCore5TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core5Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 8"]

[Cpu0DtsCore6TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core6Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 9"]

[Cpu0DtsCore7TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core7Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 10"]

[Cpu0DtsCore8TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core8Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 11"]

[Cpu0DtsCore9TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core9Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 12"]

[Cpu0DtsCore10TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core10Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 13"]

[Cpu0DtsCore11TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core11Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 14"]

[Cpu0DtsCore12TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core12Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 15"]

[Cpu0DtsCore13TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core13Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 16"]

[Cpu0DtsCore14TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core14Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 17"]

[Cpu0DtsCore15TempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-Core15Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 18"]

[Cpu0DtsPackageTempInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-CPU0-DTS-PackageTemp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 19"]

[Cpu0DtsPackageTempLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
X=-4r
Y=r
Text="Package Temperature"

[Cpu0DtsThermalThrottlingInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
X=4r
Text="#HWiNFO-CPU0-DTS-PackageTt#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextCpu0Dts "Executebatch 20"]

[Cpu0DtsThermalThrottlingLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
X=-4r
Y=r
Text="Thermal Throttling"

; ----- MOBO -----

[MoboLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoSectionLabel
Text="Motherboard"

[MoboSensorIdLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor ID"

[MoboSensorInstanceLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor Instance"

[MoboCpuFanLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="CPU Fan"

[MoboSensorIdInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
X=(#hwinfoColumnX# + 1)
Y=[MoboSensorIdLabelString:Y]
Text="#HWiNFO-MOBO-SensorId#"
DynamicVariables=1
LeftMouseUpAction=[!CommandMeasure MeasureInputTextMobo "Executebatch 1"]

[MoboSensorInstanceInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-MOBO-SensorInstance#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextMobo "Executebatch 2"]

[MoboCpuFanInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-MOBO-CpuFan#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextMobo "Executebatch 3"]

; ----- Footer -----

[CpuMeterNavString]
Meter=String
MeterStyle=StyleString
FontSize=10
Y=10R
Text="CPU Meter"

[GpuMeterNavString]
Meter=String
MeterStyle=StyleString
FontSize=10
X=10R
Y=r
Text="GPU Meter"
MouseOverAction=[!SetOption GpuMeterNavString FontColor "#colorButtonPress#"][!UpdateMeter GpuMeterNavString][!Redraw]
MouseLeaveAction=[!SetOption GpuMeterNavString FontColor ""][!UpdateMeter GpuMeterNavString][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables page "gpu"][!Refresh]

[CpuMeterNavBar]
Meter=Image
SolidColor=#colorAccent#
X=[CpuMeterNavString:X]
Y=R
W=[CpuMeterNavString:W]
H=1
DynamicVariables=1

[HwinfoSmvButton]
Meter=Image
ImageName=#imgPath#HWiNFO.png
ImageAlpha=#colorBgA#
X=(#contentMarginRight# - 13)
Y=-14r
W=15
H=15
Antialias=1
ToolTipText="Open HWiNFO Shared Memory Viewer"
MouseOverAction=[!SetOption HwinfoSmvButton ImageTint "#colorButtonPress#"][!UpdateMeter HwinfoSmvButton][!Redraw]
MouseLeaveAction=[!SetOption HwinfoSmvButton ImageTint ""][!UpdateMeter HwinfoSmvButton][!Redraw]
LeftMouseUpAction=["#@#Addons\HWiNFO\HWiNFOSharedMemoryViewer.exe"]
DynamicVariables=1

[TutorialButton]
Meter=Image
ImageName=#imgPath#book.png
Greyscale=1
X=(-15 - 2)r
Y=r
W=15
H=15
Antialias=1
ToolTipText="View HWiNFO Tutorial"
MouseOverAction=[!SetOption TutorialButton ImageTint "#colorButtonPress#"][!UpdateMeter TutorialButton][!Redraw]
MouseLeaveAction=[!SetOption TutorialButton ImageTint ""][!UpdateMeter TutorialButton][!Redraw]
LeftMouseUpAction=["https://github.com/raiguard/ModernGadgets/wiki/Setup-Tutorial"]

[RefreshButton]
Meter=Image
ImageName=#imgPath#refresh-up.png
ImageTint=#colorAccent#
Grayscale=1
X=(-15 - 2)r
Y=r
W=15
H=15
Antialias=1
ToolTipText="Refresh gadget"
MouseOverAction=[!SetOption RefreshButton ImageName "#*imgPath*#refresh-over.png"][!UpdateMeter RefreshButton][!Redraw]
MouseLeaveAction=[!SetOption RefreshButton ImageName "#*imgPath*#refresh-up.png"][!SetOption RefreshButton ImageTint "#colorAccent#"][!UpdateMeter RefreshButton][!Redraw]
LeftMouseDownAction=[!SetOption RefreshButton ImageTint "#colorButtonPress#"][!UpdateMeter RefreshButton][!Redraw]
LeftMouseUpAction=[!Refresh ModernGadgets\CPU]

[ManualEditButton]
Meter=String
MeterStyle=StyleString
FontFace=ElegantIcons
StringAlign=Right
FontSize=10
X=-3r
Y=-1r
Text=[\x6c]
MouseOverAction=[!SetOption ManualEditButton FontColor "#colorButtonPress#"][!UpdateMeter ManualEditButton][!Redraw]
MouseLeaveAction=[!SetOption ManualEditButton FontColor ""][!UpdateMeter ManualEditButton][!Redraw]
LeftMouseUpAction=["#@#Settings\GlobalSettings.inc"]
ToolTipText="Open HWiNFO configuration file"