; ========= Measures =========

[MeasureInputTextGpu0]
Measure=Plugin
Plugin=InputText
FontColor=#colorMain#
SolidColor=#colorHwinfoBackground#
FontSize=8
FontFace=Roboto Cn
FocusDismiss=1
UpdateDivider=-1
Antialias=1
Command1=[!WriteKeyValue Variables HWiNFO-GPU0-SensorId "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-SensorId# X=[Gpu0SensorIdInputString:X] Y=[Gpu0SensorIdInputString:Y] W=[Gpu0SensorIdInputString:W] H=[Gpu0SensorIdInputString:H]
Command2=[!WriteKeyValue Variables HWiNFO-GPU0-SensorInstance "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-SensorInstance# X=[Gpu0SensorInstanceInputString:X] Y=[Gpu0SensorInstanceInputString:Y] W=[Gpu0SensorInstanceInputString:W] H=[Gpu0SensorInstanceInputString:H]
Command3=[!WriteKeyValue Variables HWiNFO-GPU0-Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-Clock# X=[Gpu0ClockInputString:X] Y=[Gpu0ClockInputString:Y] W=[Gpu0ClockInputString:W] H=[Gpu0ClockInputString:H]
Command4=[!WriteKeyValue Variables HWiNFO-GPU0-Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-Temp# X=[Gpu0TemperatureInputString:X] Y=[Gpu0TemperatureInputString:Y] W=[Gpu0TemperatureInputString:W] H=[Gpu0TemperatureInputString:H]
Command5=[!WriteKeyValue Variables HWiNFO-GPU0-CoreLoad "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-CoreLoad# X=[Gpu0CoreLoadInputString:X] Y=[Gpu0CoreLoadInputString:Y] W=[Gpu0CoreLoadInputString:W] H=[Gpu0CoreLoadInputString:H]
Command6=[!WriteKeyValue Variables HWiNFO-GPU0-MemoryClock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-MemoryClock# X=[Gpu0MemoryClockInputString:X] Y=[Gpu0MemoryClockInputString:Y] W=[Gpu0MemoryClockInputString:W] H=[Gpu0MemoryClockInputString:H]
Command7=[!WriteKeyValue Variables HWiNFO-GPU0-MemoryUsage "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-MemoryUsage# X=[Gpu0MemoryUsageInputString:X] Y=[Gpu0MemoryUsageInputString:Y] W=[Gpu0MemoryUsageInputString:W] H=[Gpu0MemoryUsageInputString:H]
Command8=[!WriteKeyValue Variables HWiNFO-GPU0-MemoryAlloc "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-MemoryAlloc# X=[Gpu0MemoryAllocInputString:X] Y=[Gpu0MemoryAllocInputString:Y] W=[Gpu0MemoryAllocInputString:W] H=[Gpu0MemoryAllocInputString:H]
Command9=[!WriteKeyValue Variables HWiNFO-GPU0-FanSpeed "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-FanSpeed# X=[Gpu0FanSpeedInputString:X] Y=[Gpu0FanSpeedInputString:Y] W=[Gpu0FanSpeedInputString:W] H=[Gpu0FanSpeedInputString:H]
Command10=[!WriteKeyValue Variables HWiNFO-GPU0-FanUsage "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-FanUsage# X=[Gpu0FanUsageInputString:X] Y=[Gpu0FanUsageInputString:Y] W=[Gpu0FanUsageInputString:W] H=[Gpu0FanUsageInputString:H]
Command11=[!WriteKeyValue Variables HWiNFO-GPU0-VideoClock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-VideoClock# X=[Gpu0VideoClockInputString:X] Y=[Gpu0VideoClockInputString:Y] W=[Gpu0VideoClockInputString:W] H=[Gpu0VideoClockInputString:H]
Command12=[!WriteKeyValue Variables HWiNFO-GPU0-MemController "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-MemController# X=[Gpu0MemControllerInputString:X] Y=[Gpu0MemControllerInputString:Y] W=[Gpu0MemControllerInputString:W] H=[Gpu0MemControllerInputString:H]
Command13=[!WriteKeyValue Variables HWiNFO-GPU0-CoreVoltage "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU0-CoreVoltage# X=[Gpu0CoreVoltageInputString:X] Y=[Gpu0CoreVoltageInputString:Y] W=[Gpu0CoreVoltageInputString:W] H=[Gpu0CoreVoltageInputString:H]

[MeasureInputTextGpu1]
Measure=Plugin
Plugin=InputText
FontColor=#colorMain#
SolidColor=#colorHwinfoBackground#
FontSize=8
FontFace=Roboto Cn
FocusDismiss=1
UpdateDivider=-1
Antialias=1
Command1=[!WriteKeyValue Variables HWiNFO-GPU1-SensorId "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-SensorId# X=[Gpu1SensorIdInputString:X] Y=[Gpu1SensorIdInputString:Y] W=[Gpu1SensorIdInputString:W] H=[Gpu1SensorIdInputString:H]
Command2=[!WriteKeyValue Variables HWiNFO-GPU1-SensorInstance "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-SensorInstance# X=[Gpu1SensorInstanceInputString:X] Y=[Gpu1SensorInstanceInputString:Y] W=[Gpu1SensorInstanceInputString:W] H=[Gpu1SensorInstanceInputString:H]
Command3=[!WriteKeyValue Variables HWiNFO-GPU1-Clock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-Clock# X=[Gpu1ClockInputString:X] Y=[Gpu1ClockInputString:Y] W=[Gpu1ClockInputString:W] H=[Gpu1ClockInputString:H]
Command4=[!WriteKeyValue Variables HWiNFO-GPU1-Temp "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-Temp# X=[Gpu1TemperatureInputString:X] Y=[Gpu1TemperatureInputString:Y] W=[Gpu1TemperatureInputString:W] H=[Gpu1TemperatureInputString:H]
Command5=[!WriteKeyValue Variables HWiNFO-GPU1-CoreLoad "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-CoreLoad# X=[Gpu1CoreLoadInputString:X] Y=[Gpu1CoreLoadInputString:Y] W=[Gpu1CoreLoadInputString:W] H=[Gpu1CoreLoadInputString:H]
Command6=[!WriteKeyValue Variables HWiNFO-GPU1-MemoryClock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-MemoryClock# X=[Gpu1MemoryClockInputString:X] Y=[Gpu1MemoryClockInputString:Y] W=[Gpu1MemoryClockInputString:W] H=[Gpu1MemoryClockInputString:H]
Command7=[!WriteKeyValue Variables HWiNFO-GPU1-MemoryUsage "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-MemoryUsage# X=[Gpu1MemoryUsageInputString:X] Y=[Gpu1MemoryUsageInputString:Y] W=[Gpu1MemoryUsageInputString:W] H=[Gpu1MemoryUsageInputString:H]
Command8=[!WriteKeyValue Variables HWiNFO-GPU1-MemoryAlloc "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-MemoryAlloc# X=[Gpu1MemoryAllocInputString:X] Y=[Gpu1MemoryAllocInputString:Y] W=[Gpu1MemoryAllocInputString:W] H=[Gpu1MemoryAllocInputString:H]
Command9=[!WriteKeyValue Variables HWiNFO-GPU1-FanSpeed "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-FanSpeed# X=[Gpu1FanSpeedInputString:X] Y=[Gpu1FanSpeedInputString:Y] W=[Gpu1FanSpeedInputString:W] H=[Gpu1FanSpeedInputString:H]
Command10=[!WriteKeyValue Variables HWiNFO-GPU1-FanUsage "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-FanUsage# X=[Gpu1FanUsageInputString:X] Y=[Gpu1FanUsageInputString:Y] W=[Gpu1FanUsageInputString:W] H=[Gpu1FanUsageInputString:H]
Command11=[!WriteKeyValue Variables HWiNFO-GPU1-VideoClock "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-VideoClock# X=[Gpu1VideoClockInputString:X] Y=[Gpu1VideoClockInputString:Y] W=[Gpu1VideoClockInputString:W] H=[Gpu1VideoClockInputString:H]
Command12=[!WriteKeyValue Variables HWiNFO-GPU1-MemController "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-MemController# X=[Gpu1MemControllerInputString:X] Y=[Gpu1MemControllerInputString:Y] W=[Gpu1MemControllerInputString:W] H=[Gpu1MemControllerInputString:H]
Command13=[!WriteKeyValue Variables HWiNFO-GPU1-CoreVoltage "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-GPU1-CoreVoltage# X=[Gpu1CoreVoltageInputString:X] Y=[Gpu1CoreVoltageInputString:Y] W=[Gpu1CoreVoltageInputString:W] H=[Gpu1CoreVoltageInputString:H]

[MeasureInputTextMobo]
Measure=Plugin
Plugin=InputText
FontColor=#colorMain#
SolidColor=#colorHwinfoBackground#
FontSize=8
FontFace=Roboto Cn
FocusDismiss=1
UpdateDivider=-1
Antialias=1
Command1=[!WriteKeyValue Variables HWiNFO-MOBO-GpuFan "$UserInput$" "#globalSettingsPath#"][!Refresh] DefaultValue=#HWiNFO-MOBO-GpuFan# X=[MoboGpuFanInputString:X] Y=[MoboGpuFanInputString:Y] W=[MoboGpuFanInputString:W] H=[MoboGpuFanInputString:H]

; ========= Meters =========

[Gpu0Gpu1LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoSectionLabel
Text="GPU0 / GPU1"

[Gpu0LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
StringAlign=Left
X=(#hwinfoColumnX# + 21)
Text="GPU0"

[SensorIdLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor ID"

[SensorInstanceLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor Instance"

[ClockLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="GPU Clock"

[TemperatureLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Temperature"

[CoreLoadLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core Load"

[MemoryClockLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Memory Clock"

[MemoryUsageLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="VRAM Usage"

[MemoryAllocLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="VRAM Allocated"

[FanSpeedLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Fan Speed"

[FanUsageLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Fan Usage"

[VideoClockLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Video Clock"

[MemControllerLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Mem. Controller"

[CoreVoltageLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Core Voltage"

[Gpu0SensorIdInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
X=(#hwinfoColumnX# + 1)
Y=[SensorIdLabelString:Y]
Text="#HWiNFO-GPU0-SensorId#"
DynamicVariables=1
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 1"]

[Gpu0SensorInstanceInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-SensorInstance#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 2"]

[Gpu0ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 3"]

[Gpu0TemperatureInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 4"]

[Gpu0CoreLoadInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-CoreLoad#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 5"]

[Gpu0MemoryClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-MemoryClock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 6"]

[Gpu0MemoryUsageInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-MemoryUsage#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 7"]

[Gpu0MemoryAllocInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-MemoryAlloc#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 8"]

[Gpu0FanSpeedInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-FanSpeed#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 9"]

[Gpu0FanUsageInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-FanUsage#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 10"]

[Gpu0VideoClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-VideoClock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 11"]

[Gpu0MemControllerInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-MemController#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 12"]

[Gpu0CoreVoltageInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU0-CoreVoltage#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu0 "Executebatch 13"]

[Gpu1LabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
StringAlign=Left
X=23R
Y=[Gpu0LabelString:Y]
Text="GPU1"
DynamicVariables=1

[Gpu1SensorIdInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
X=-20r
Text="#HWiNFO-GPU1-SensorId#"
DynamicVariables=1
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 1"]

[Gpu1SensorInstanceInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-SensorInstance#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 2"]

[Gpu1ClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-Clock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 3"]

[Gpu1TemperatureInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-Temp#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 4"]

[Gpu1CoreLoadInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-CoreLoad#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 5"]

[Gpu1MemoryClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-MemoryClock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 6"]

[Gpu1MemoryUsageInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-MemoryUsage#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 7"]

[Gpu1MemoryAllocInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-MemoryAlloc#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 8"]

[Gpu1FanSpeedInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-FanSpeed#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 9"]

[Gpu1FanUsageInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-FanUsage#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 10"]

[Gpu1VideoClockInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-VideoClock#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 11"]

[Gpu1MemControllerInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-MemController#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 12"]

[Gpu1CoreVoltageInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-GPU1-CoreVoltage#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextGpu1 "Executebatch 13"]

; ----- Motherboard -----

[MoboLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoSectionLabel
Y=10R
Text="Motherboard"

[MoboSensorIdLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor ID"

[MoboSensorInstanceLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="Sensor Instance"

[MoboGpuFanLabelString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoLabel
Text="GPU Fan"

[MoboSensorIdString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
FontColor=#colorInfo#
X=(#hwinfoColumnX# + 1)
Y=[MoboSensorIdLabelString:Y]
Text="#HWiNFO-MOBO-SensorId#"
DynamicVariables=1

[MoboSensorInstanceString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
FontColor=#colorInfo#
Text="#HWiNFO-MOBO-SensorInstance#"

[MoboGpuFanInputString]
Meter=String
MeterStyle=StyleString | StyleStringHwinfoInput
Text="#HWiNFO-MOBO-GpuFan#"
LeftMouseUpAction=[!CommandMeasure MeasureInputTextMobo "Executebatch 1"]

[MoboGpuFanInfoString]
Meter=String
MeterStyle=StyleString | StyleStringParagraph
FontColor=#colorInfo#
FontSize=8
X=3R
Y=([MoboSensorIdLabelString:Y] - 2)
W=(#contentMarginRight# - [MoboGpuFanInfoString:X])
Text="If the GPU Fan is under the motherboard group, configure it here and enable the toggle in GPU Meter's settings."
DynamicVariables=1

; ----- Nav Bar -----

[CpuMeterNavString]
Meter=String
MeterStyle=StyleString
FontSize=10
Y=10R
Text="CPU Meter"
MouseOverAction=[!SetOption CpuMeterNavString FontColor "#colorButtonPress#"][!UpdateMeter CpuMeterNavString][!Redraw]
MouseLeaveAction=[!SetOption CpuMeterNavString FontColor ""][!UpdateMeter CpuMeterNavString][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Variables page "cpu"][!Refresh]

[GpuMeterNavString]
Meter=String
MeterStyle=StyleString
FontSize=10
X=10R
Y=r
Text="GPU Meter"

[GpuMeterNavBar]
Meter=Image
SolidColor=#colorAccent#
X=[GpuMeterNavString:X]
Y=R
W=[GpuMeterNavString:W]
H=1
DynamicVariables=1

[HwinfoSmvButton]
Meter=Image
ImageName=#imgPath#HWiNFO.png
ImageAlpha=#colorBgA#
X=(#contentMarginRight# - 13)
Y=-14r
W=15
H=15
Antialias=1
ToolTipText="Open HWiNFO Shared Memory Viewer"
MouseOverAction=[!SetOption HwinfoSmvButton ImageTint "#colorButtonPress#"][!UpdateMeter HwinfoSmvButton][!Redraw]
MouseLeaveAction=[!SetOption HwinfoSmvButton ImageTint ""][!UpdateMeter HwinfoSmvButton][!Redraw]
LeftMouseUpAction=["#@#Addons\HWiNFO\HWiNFOSharedMemoryViewer.exe"]
DynamicVariables=1

[TutorialButton]
Meter=Image
ImageName=#imgPath#book.png
Greyscale=1
X=(-15 - 2)r
Y=r
W=15
H=15
Antialias=1
ToolTipText="View HWiNFO Tutorial"
MouseOverAction=[!SetOption TutorialButton ImageTint "#colorButtonPress#"][!UpdateMeter TutorialButton][!Redraw]
MouseLeaveAction=[!SetOption TutorialButton ImageTint ""][!UpdateMeter TutorialButton][!Redraw]
LeftMouseUpAction=["https://github.com/raiguard/ModernGadgets/wiki/Setup-Tutorial"]

[RefreshButton]
Meter=Image
ImageName=#imgPath#refresh-up.png
ImageTint=#colorAccent#
Grayscale=1
X=(-15 - 2)r
Y=r
W=15
H=15
Antialias=1
ToolTipText="Refresh gadget"
MouseOverAction=[!SetOption RefreshButton ImageName "#*imgPath*#refresh-over.png"][!UpdateMeter RefreshButton][!Redraw]
MouseLeaveAction=[!SetOption RefreshButton ImageName "#*imgPath*#refresh-up.png"][!SetOption RefreshButton ImageTint "#colorAccent#"][!UpdateMeter RefreshButton][!Redraw]
LeftMouseDownAction=[!SetOption RefreshButton ImageTint "#colorButtonPress#"][!UpdateMeter RefreshButton][!Redraw]
LeftMouseUpAction=[!Refresh ModernGadgets\GPU]

[ManualEditButton]
Meter=String
MeterStyle=StyleString
FontFace=ElegantIcons
StringAlign=Right
FontSize=10
X=-3r
Y=-1r
Text=[\x6c]
MouseOverAction=[!SetOption ManualEditButton FontColor "#colorButtonPress#"][!UpdateMeter ManualEditButton][!Redraw]
MouseLeaveAction=[!SetOption ManualEditButton FontColor ""][!UpdateMeter ManualEditButton][!Redraw]
LeftMouseUpAction=["#@#Settings\GlobalSettings.inc"]
ToolTipText="Open HWiNFO configuration file"