[Variables]

bgHeight=225

; -- User settings --

showGpuName=1
showMemController=1
showShaderClock=1
showCoreVoltage=0
showGraph=1

; -- Colors --
colorTotalUsage=255,246,42,200
colorMemoryUsage=107,198,250,200
colorFanUsage=107,238,98,200
colorMemController=250,158,0,200

; -- Dynamic (do not change) --

; Colors
colorTotalUsageRgb=0,0,0
colorMemoryUsageRgb=0,0,0
colorFanUsageRgb=0,0,0
colorMemControllerRgb=0,0,0

colorTotalUsageA=0
colorMemoryUsageA=0
colorFanUsageA=0
colorMemControllerA=0

; Text
textMemoryUsedGpu0=
textMemoryTotalGpu0=
