[Variables]

bgHeight=147

; -- User settings --
showRefreshButtons=1
showGraph=1

fpfDepth=5

; -- Colors --
colorUpload=107,238,98,200
colorDownload=255,246,42,200

; -- Interfaces --
;
; Set the interface identifiers to match your system.  If your machine does not have have an adapter
; of the specified type or to turn off monitoring, use 0 as the identifier.  Set all interfaces to 0
; to have rainmeter report on all adapters, but if you have any virtualized interfaces active, the
; NetIn/NetOut/NetTotal measures will be incorrect.  See http://docs.rainmeter.net/tips/network-skin
; for an explanation and details on how to find your network interface indentifiers.  Use the
; Settings gadget to configure these values or enter them here.  Unless you have a machine with
; multiple network cards installed (i.e., like a server), you should only have one ACTIVE PHYSICAL
; network interface of each type, all other reported interfaces should be virtual or disconnected.
;
interfaceBroadband=0
interfaceEthernet=0
interfaceWireless=0

; -- Dynamic (do not change) --

; Colors
colorUploadRgb=0,0,0
colorDownloadRgb=0,0,0

colorUploadA=0
colorDownloadA=0

; Data
dataIsInbound=0
dataIsOutbound=0
disableBroadband=0
disableEthernet=0
disableWireless=0
maxBytesPerSec=0

; Text
textNetIn=""
textNetInBits=""
textNetInBytesCurrent=""
textNetInBytesTotal=""
textNetOut=""
textNetOutBits=""
textNetOutBytesCurrent=""
textNetOutBytesTotal=""
