[Variables]
timeAmPmSize=12
showSystemUptime=1
showEventCountdown=1

eventName=19th Birthday
eventTimestamp=2019-03-02 00:00:00

timeFormat=WinLong
dateFormat=WinLong
customTimeFormat=%I:%M:%S %p
customDateFormat=%m.%d.%G

locale=en-US

; Colors
colorStopwatchMain=107,238,98
colorStopwatchLap=255,246,42

colorStopwatchStart=50,240,50
colorStopwatchLapButton=255,246,42
colorStopwatchStop=240,50,50
colorStopwatchPauseButton=100,100,200
colorStopwatchResetButton=#colorDim#
