[Variables]
lineGraphAa=1
lineGraphBgType=1
tempUnits=C

scale=1
tScale=1

cornerRoundness=3

notifyUpdates=1
updateCheckRate=90
autoBackups=1
checkForPrereleases=1

updateNotificationSound="C:\Windows\media\notify.wav"
useUpdateNotificationSound=1

showBgBorder=1
rowSpacing=1
barTextOffset=1
barHeight=1
graphHeight=42
graphWidth=#contentWidth#

; Sidebars
setupSb=1
sbSetupMode=Placement

sb1Enabled=0
sb1MaskType=acrylic
sb1MaskColor=0,0,0
sb1MaskAlpha=150
sb1Columns=1
sb1Alignment=left
sb1Monitor=1

sb2Enabled=0
sb2MaskType=acrylic
sb2MaskColor=0,0,0
sb2MaskAlpha=150
sb2Columns=1
sb2Alignment=right
sb2Monitor=2

colorSbControlCorner=0,0,3

colorBorder=50,50,50
colorBg=15,15,15
colorBgBorder=#colorBorder#
colorSubBg=25,25,25

colorGraphBg=#colorSubBg#
colorGraphBorder=#colorBorder#

colorMain=230,230,230
colorDim=175,175,175
colorAccent=137,190,250
colorDisabled=120,120,120,200

colorBarBg=#colorBorder#

colorButtonPress=200,50,50

colorInputBg=#colorSubBg#
colorInputBorder=#colorBorder#
colorInputText=#colorDim#

colorIntel=0,125,198
