[Variables]
showAvgUsage=0
showBars=1
showLineGraph=1

processes=10
processMode=1
processBlacklist=_Total|Idle|dwm|csrss|svchost|lsass|System|spoolsv

fpfProcessCpuDepth=3
fpfProcessRamDepth=3
fpfProcessGpuDepth=3
fpfProcessVramDepth=3

; Colors
colorProcess1=107,238,98
colorProcess2=255,246,42
colorProcess3=250,158,0
colorProcess4=236,28,70
colorProcess5=199,36,199
colorProcess6=145,70,232
colorProcess7=42,112,250
colorProcess8=43,224,224
colorProcess9=121,182,62
colorProcess10=204,255,0

colorCpuUsage=107,238,98
colorGpuUsage=107,238,98

; HWiNFO
HWiNFO-GPU0-CoreLoad-SensorId=0xe0002000
HWiNFO-GPU0-CoreLoad-SensorInstance=0x0
HWiNFO-GPU0-CoreLoad-EntryId=0x7000000

[HWiNFO-Config-GPU0]
HWiNFO-GPU0-CoreLoad=GPU Core Load (%)
