[Variables]
; dark sky api key - keep this a secret!
apiKey=
; coordinates
lat=40.3491173
lon=-111.9046567
; location name
location=Saratoga Springs
; units: one of "si", "ca", "uk2", "us", or "auto"
units=auto
; language
language=en

showHumidity=1
showUv=1
showUvChart=1
showAtmPressure=0
showVisibility=1
showDewpoint=0
showWindInfo=1
showSunMoonInfo=1
showMoonAngle=1

timeFormat=WinShort
customTimeFormat=%#I:%M %p
