[Variables]
; LocationCode can be obtained at http://wxdata.weather.com/wxdata/search/search?where=YourCityName
locationCode=USUT0281
; UnitOfMeasure can be "f" (Fahrenheit / Imperial) or "m" (Celsius / Metric)
unitOfMeasure=f
; Locale (language) to use in the feed.
; https://msdn.microsoft.com/en-us/goglobal/bb896001.aspx
; Note that Weather.com uses "_" underline instead of "-" dash in the codes.
locale=en_US

weatherUpdateRate=10

showHumidity=1
showUv=1
showUvChart=1
showAtmPressure=0
showVisibility=1
showDewpoint=0
showWindInfo=1
showSunMoonInfo=1
showMoonAngle=1

timeFormat=WinShort
dateFormat=WinShort
customTimeFormat=%#I:%M %p
customDateFormat=%m/%d/%y
