[TitleString]
Meter=String
MeterStyle=StyleString
FontSize=23
FontColor=#fontColorAccent#
StringAlign=Center
X=#bgCenterX#
Y=#contentMargin#
Text="Modern Gadgets"

[StatusString]
Meter=String
MeterStyle=StyleString
StringAlign=Center
FontSize=11
X=#bgCenterX#
Text="Performing initial setup"

[SetupProgressBar]
Meter=Bar
MeasureName=MeasureSetupProgress
MeterStyle=StyleBar
X=(#bgCenterX# - 100)
Y=5R
W=200
BarColor=#fontColorDim#
