[LogoGears]
Meter=Image
ImageName=#imgPath#LogoGears.png
X=(#contentMargin# + 4)
Y=(#contentMargin# + 4)
W=26
H=45

[LogoNameString]
Meter=String
MeterStyle=StyleString
FontSize=26
X=R
Y=-5r
Text="ModernGadgets"

[LogoSubtitleString]
Meter=String
MeterStyle=StyleString
FontSize=10
FontColor=#colorInfo#
X=5r
Y=-10R
Text="System monitoring - evolved"

[UpdateAvailableString]
Meter=String
MeterStyle=StyleString | StyleStringCenterAlign
FontSize=12
Y=5R
Text="An update is available!"

[VersionString]
Meter=String
MeterStyle=StyleString | StyleStringCenterAlign
FontSize=10
Text="v#releaseVer#"
DynamicVariables=1
