[Variables]
timeAmPmSize=12
showSystemUptime=1
showEventCountdown=1

eventName=developer leaves
eventTimestamp=2019-09-18 10:00:00

timeFormat=WinLong
dateFormat=WinLong
customTimeFormat=%#I:%M:%S %p
customDateFormat=%m.%d.%G

locale=en-US

; DEBUGGING VARIABLES
alarm1Time=12:30
alarm2Time=18:13
enableAlarm1=0
enableAlarm2=0

alarm1Sound=C:\Windows\Media\Alarm01.wav
alarm2Sound=C:\Windows\Media\Alarm02.wav
alarm1Duration=60
alarm2Duration=60

timerFinishedSound=C:\Windows\Media\Alarm05.wav

; Colors
colorStopwatchMain=107,238,98
colorStopwatchLap=255,246,42

colorStopwatchStart=50,240,50
colorStopwatchLapButton=255,246,42
colorStopwatchStop=240,50,50
colorStopwatchPauseButton=100,100,200
colorStopwatchResetButton=#colorDim#
