; MODERNGADGETS "CPU" SETTINGS FILE

[Variables]
tempUom=C
ttSoundPath=D:\Caleb\Development\Rainmeter\Projects\ModernGadgets\Skins\ModernGadgets\@Resources\Assets\Sounds\alarmalerteffect.wav

; Set automatically - don't bother changing (they will just change back)
cpuName=auto
threadCount=8

; Fixed precision format
fpfRamDepth=4
fpfPageDepth=4

; Colors
colorRam=107,198,250
colorPage=255,204,0
colorTempGraph=200,0,0
colorCpuFan=150,150,150
colorAvgCpu=237,28,32
ttHistogramAlpha=70
colorTt=255,100,100
colorCore1=107,238,98
colorCore2=255,246,42
colorCore3=250,158,0
colorCore4=236,28,70
colorCore5=199,36,199
colorCore6=145,70,232
colorCore7=42,112,250
colorCore8=43,224,224
colorCore9=121,182,62
colorCore10=204,255,0
colorCore11=250,205,22
colorCore12=191,100,55
colorCore13=201,41,56
colorCore14=179,0,91
colorCore15=153,84,166
colorCore16=99,125,217
colorCore17=#colorCore1#
colorCore18=#colorCore2#
colorCore19=#colorCore3#
colorCore20=#colorCore4#
colorCore21=#colorCore5#
colorCore22=#colorCore6#
colorCore23=#colorCore7#
colorCore24=#colorCore8#
colorCore25=#colorCore9#
colorCore26=#colorCore10#
colorCore27=#colorCore11#
colorCore28=#colorCore12#
colorCore29=#colorCore13#
colorCore30=#colorCore14#
colorCore31=#colorCore15#
colorCore32=#colorCore16#


showCpuName=1
showPageFile=0
showCoreTemps=1
showCoreVoltages=1
showCpuTempGraph=1
showTopProcess=1
showCpuFan=1
showCpuClock=1
showLineGraph=1
showAvgCpu=0
showTt=0
playTtSound=0

isHwinfoAvailable=1
useHwinfoClock=1

; ====== DEFAULTS ======

dColorRam=107,198,250
dColorPage=255,204,0
dColorCpuFan=150,150,150
dColorAvgCpu=237,28,32
dColorCore1=107,238,98
dColorCore2=255,246,42
dColorCore3=250,158,0
dColorCore4=236,28,70
dColorCore5=199,36,199
dColorCore6=145,70,232
dColorCore7=42,112,250
dColorCore8=43,224,224
dColorCore9=121,182,62
dColorCore10=204,255,0
dColorCore11=250,205,22
dColorCore12=191,100,55
dColorCore13=201,41,56
dColorCore14=179,0,91
dColorCore15=153,84,166
dColorCore16=99,125,217
dColorTt=255,120,147
dTtHistogramAlpha=50
;====== DEFAULTS ======
;====== DEFAULTS ======
