; DISKS METER SETTINGS
[Variables]
fpfReadDepth=4
fpfWriteDepth=4
fpfSpaceUsedDepth=5
fpfSpaceTotalDepth=5

manualHideDisks=
unnamedDiskLabel=---

diskCommand="C:\Windows\explorer.exe" /E,{drive}\
histogramA=50

ignoreRemovable=0

showEjectButtons=1
showDiskTemps=1
showDiskReadWrite=1
showLineGraph=1
showHistograms=1

colorDisk1=107,238,98
colorDisk2=255,246,42
colorDisk3=250,158,0
colorDisk4=236,28,70
colorDisk5=199,36,199
colorDisk6=145,70,232
colorDisk7=42,112,250
colorDisk8=43,224,224
colorDisk9=121,182,62
colorDisk10=204,255,0
colorDisk11=250,205,22
colorDisk12=191,100,55
colorDisk13=201,41,56
colorDisk14=179,0,91
colorDisk15=153,84,166
colorDisk16=99,125,217
colorDisk17=107,238,98
colorDisk18=255,246,42
colorDisk19=250,158,0
colorDisk20=236,28,70
colorDisk21=199,36,199
colorDisk22=145,70,232
colorDisk23=42,112,250
colorDisk24=43,224,224
colorDisk25=121,182,62
colorDisk26=204,255,0

; ====== DEFAULTS ======

dColorDisk1=107,238,98
dColorDisk2=255,246,42
dColorDisk3=250,158,0
dColorDisk4=236,28,70
dColorDisk5=199,36,199
dColorDisk6=145,70,232
dColorDisk7=42,112,250
dColorDisk8=43,224,224
dColorDisk9=121,182,62
dColorDisk10=204,255,0
dColorDisk11=250,205,22
dColorDisk12=191,100,55
dColorDisk13=201,41,56
dColorDisk14=179,0,91
dColorDisk15=153,84,166
dColorDisk16=99,125,217
dColorDisk17=107,238,98
dColorDisk18=255,246,42
dColorDisk19=250,158,0
dColorDisk20=236,28,70
dColorDisk21=199,36,199
dColorDisk22=145,70,232
dColorDisk23=42,112,250
dColorDisk24=43,224,224
dColorDisk25=121,182,62
dColorDisk26=204,255,0

; ====== HWiNFO ======

; Disk A
HWiNFO-SMART-DiskATemp-SensorId=0xf0000100
HWiNFO-SMART-DiskATemp-SensorInstance=0x0
HWiNFO-SMART-DiskATemp-EntryId=0x0
; Disk B
HWiNFO-SMART-DiskBTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskBTemp-SensorInstance=0x0
HWiNFO-SMART-DiskBTemp-EntryId=0x0
; Disk C
HWiNFO-SMART-DiskCTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskCTemp-SensorInstance=0x0
HWiNFO-SMART-DiskCTemp-EntryId=0x1000001
; Disk D
HWiNFO-SMART-DiskDTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskDTemp-SensorInstance=0x1
HWiNFO-SMART-DiskDTemp-EntryId=0x1000000
; Disk E
HWiNFO-SMART-DiskETemp-SensorId=0xf0000100
HWiNFO-SMART-DiskETemp-SensorInstance=0x2
HWiNFO-SMART-DiskETemp-EntryId=0x1000000
; Disk F
HWiNFO-SMART-DiskFTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskFTemp-SensorInstance=0x0
HWiNFO-SMART-DiskFTemp-EntryId=0x0
; Disk G
HWiNFO-SMART-DiskGTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskGTemp-SensorInstance=0x0
HWiNFO-SMART-DiskGTemp-EntryId=0x0
; Disk H
HWiNFO-SMART-DiskHTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskHTemp-SensorInstance=0x0
HWiNFO-SMART-DiskHTemp-EntryId=0x0
; Disk I
HWiNFO-SMART-DiskITemp-SensorId=0xf0000100
HWiNFO-SMART-DiskITemp-SensorInstance=0x0
HWiNFO-SMART-DiskITemp-EntryId=0x0
; Disk J
HWiNFO-SMART-DiskJTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskJTemp-SensorInstance=0x0
HWiNFO-SMART-DiskJTemp-EntryId=0x0
; Disk K
HWiNFO-SMART-DiskKTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskKTemp-SensorInstance=0x0
HWiNFO-SMART-DiskKTemp-EntryId=0x0
; Disk L
HWiNFO-SMART-DiskLTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskLTemp-SensorInstance=0x0
HWiNFO-SMART-DiskLTemp-EntryId=0x0
; Disk M
HWiNFO-SMART-DiskMTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskMTemp-SensorInstance=0x0
HWiNFO-SMART-DiskMTemp-EntryId=0x0
; Disk N
HWiNFO-SMART-DiskNTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskNTemp-SensorInstance=0x0
HWiNFO-SMART-DiskNTemp-EntryId=0x0
; Disk O
HWiNFO-SMART-DiskOTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskOTemp-SensorInstance=0x0
HWiNFO-SMART-DiskOTemp-EntryId=0x0
; Disk P
HWiNFO-SMART-DiskPTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskPTemp-SensorInstance=0x0
HWiNFO-SMART-DiskPTemp-EntryId=0x0
; Disk Q
HWiNFO-SMART-DiskQTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskQTemp-SensorInstance=0x0
HWiNFO-SMART-DiskQTemp-EntryId=0x0
; Disk R
HWiNFO-SMART-DiskRTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskRTemp-SensorInstance=0x0
HWiNFO-SMART-DiskRTemp-EntryId=0x0
; Disk S
HWiNFO-SMART-DiskSTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskSTemp-SensorInstance=0x0
HWiNFO-SMART-DiskSTemp-EntryId=0x0
; Disk T
HWiNFO-SMART-DiskTTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskTTemp-SensorInstance=0x0
HWiNFO-SMART-DiskTTemp-EntryId=0x0
; Disk U
HWiNFO-SMART-DiskUTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskUTemp-SensorInstance=0x0
HWiNFO-SMART-DiskUTemp-EntryId=0x0
; Disk V
HWiNFO-SMART-DiskVTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskVTemp-SensorInstance=0x0
HWiNFO-SMART-DiskVTemp-EntryId=0x0
; Disk W
HWiNFO-SMART-DiskWTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskWTemp-SensorInstance=0x0
HWiNFO-SMART-DiskWTemp-EntryId=0x0
; Disk X
HWiNFO-SMART-DiskXTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskXTemp-SensorInstance=0x0
HWiNFO-SMART-DiskXTemp-EntryId=0x0
; Disk Y
HWiNFO-SMART-DiskYTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskYTemp-SensorInstance=0x0
HWiNFO-SMART-DiskYTemp-EntryId=0x0
; Disk Z
HWiNFO-SMART-DiskZTemp-SensorId=0xf0000100
HWiNFO-SMART-DiskZTemp-SensorInstance=0x0
HWiNFO-SMART-DiskZTemp-EntryId=0x0

[HWiNFO-Config]

[HWiNFO-Config-Temperatures]
HWiNFO-SMART-DiskATemp=Disk A Temperature
HWiNFO-SMART-DiskBTemp=Disk B Temperature
HWiNFO-SMART-DiskCTemp=Disk C Temperature
HWiNFO-SMART-DiskDTemp=Disk D Temperature
HWiNFO-SMART-DiskETemp=Disk E Temperature
HWiNFO-SMART-DiskFTemp=Disk F Temperature
HWiNFO-SMART-DiskGTemp=Disk G Temperature
HWiNFO-SMART-DiskHTemp=Disk H Temperature
HWiNFO-SMART-DiskITemp=Disk I Temperature
HWiNFO-SMART-DiskJTemp=Disk J Temperature
HWiNFO-SMART-DiskKTemp=Disk K Temperature
HWiNFO-SMART-DiskLTemp=Disk L Temperature
HWiNFO-SMART-DiskMTemp=Disk M Temperature
HWiNFO-SMART-DiskNTemp=Disk N Temperature
HWiNFO-SMART-DiskOTemp=Disk O Temperature
HWiNFO-SMART-DiskPTemp=Disk P Temperature
HWiNFO-SMART-DiskQTemp=Disk Q Temperature
HWiNFO-SMART-DiskRTemp=Disk R Temperature
HWiNFO-SMART-DiskSTemp=Disk S Temperature
HWiNFO-SMART-DiskTTemp=Disk T Temperature
HWiNFO-SMART-DiskUTemp=Disk U Temperature
HWiNFO-SMART-DiskVTemp=Disk V Temperature
HWiNFO-SMART-DiskWTemp=Disk W Temperature
HWiNFO-SMART-DiskXTemp=Disk X Temperature
HWiNFO-SMART-DiskYTemp=Disk Y Temperature
HWiNFO-SMART-DiskZTemp=Disk Z Temperature
