[Variables]
lineGraphAa=0
tempUnits=C
isHwinfoAvailable=1

gadgetUpdateRate=1000

notifyUpdates=1
devUpdates=0
autoBackups=1
rVersionKey=stable

showBgBorder=1
largeRowSpacing=0
rowSpacing=1

colorMain=230,230,230
colorInfo=150,150,150
colorDim=50,50,50
colorAccent=138,210,250

colorBg=15,15,15
colorBgBorder=50,50,50
colorBarBg=#colorBgBorder#

colorButtonPress=255,50,50
colorInputBg=25,25,25
colorInputBorder=#colorDim#

; ----- Default Colors -----

dColorMain=230,230,230
dColorInfo=150,150,150
dColorDim=50,50,50
dColorAccent=138,210,250

dColorBg=15,15,15
dColorBgBorder=50,50,50
dColorBarBg=#colorDim#

dColorButtonPress=255,50,50
