[Variables]
lineGraphAa=0
tempUnits=C
isHwinfoAvailable=1

gadgetUpdateRate=1000

notifyUpdates=1
autoBackups=1
rVersionKey=dev

showBgBorder=0
largeRowSpacing=0
rowSpacing=1

colorBorder=50,50,50
colorBg=15,15,15
colorBgBorder=#colorBorder#
colorSubBg=25,25,25

colorGraphBg=#colorSubBg#
colorGraphBorder=#colorBorder#

colorMain=230,230,230
colorInfo=150,150,150
colorAccent=138,210,250

colorBarBg=#colorBorder#

colorButtonPress=200,50,50

colorInputBg=#colorSubBg#
colorInputBorder=#colorBorder#

colorIntel=0,125,198

; ----- Default Colors -----

dColorMain=230,230,230
dColorInfo=150,150,150
dColorSubBg=25,25,25
dColorBorder=50,50,50
dColorAccent=138,210,250

dColorBg=15,15,15
dColorBgBorder=50,50,50
dColorBarBg=#colorDim#

dColorButtonPress=255,50,50
