; MODERNGADGETS GLOBAL SETTINGS

[Variables]

lineGraphAa=0
tempUnits=C
isHwinfoAvailable=1

notifyUpdates=1
devUpdates=0
autoBackups=1

showBgBorder=1
largeRowSpacing=0

; Color pallete
colorPallete1=107,198,250,240
colorPallete2=255,204,0,240
colorPallete3=150,150,150,240
colorPallete4=236,28,70,240
colorPallete5=107,238,98,240
colorPallete6=255,246,42,240
colorPallete7=250,158,0,240
colorPallete8=236,28,70,240
colorPallete9=199,36,199,240
colorPallete10=145,70,232,240
colorPallete11=42,112,250,240
colorPallete12=43,224,224,240
colorPallete13=121,182,62,240
colorPallete14=204,255,0,240
colorPallete15=250,205,22,240
colorPallete16=191,100,55,240
colorPallete17=201,41,56,240
colorPallete18=179,0,91,240
colorPallete19=153,84,166,240
colorPallete20=99,125,217,240

; ----- HWiNFO -----

;
; CPU 0
;
; sensor ID and instance
HWiNFO-CPU0-SensorId=0xf0000300
HWiNFO-CPU0-SensorInstance=0x0
; entry IDs
; core 0 clock frequency (MHz)
HWiNFO-CPU0-Core0Clock=0x6000000
; core 1 clock frequency (MHz)
HWiNFO-CPU0-Core1Clock=0x6000001
; core 2 clock frequency (MHz)
HWiNFO-CPU0-Core2Clock=0x6000002
; core 3 clock frequency (MHz)
HWiNFO-CPU0-Core3Clock=0x6000003
; core 4 clock frequency (MHz)
HWiNFO-CPU0-Core4Clock=0x6000004
; core 5 clock frequency (MHz)
HWiNFO-CPU0-Core5Clock=0x6000005
; core 6 clock frequency (MHz)
HWiNFO-CPU0-Core6Clock=0x6000006
; core 7 clock frequency (MHz)
HWiNFO-CPU0-Core7Clock=0x6000007
; core 8 clock frequency (MHz)
HWiNFO-CPU0-Core8Clock=0x6000008
; core 9 clock frequency (MHz)
HWiNFO-CPU0-Core9Clock=0x6000009
; core 0 voltage (volts)
HWiNFO-CPU0-Core0VID=0x2000000
; core 1 voltage (volts)
HWiNFO-CPU0-Core1VID=0x2000001
; core 2 voltage (volts)
HWiNFO-CPU0-Core2VID=0x2000002
; core 3 voltage (volts)
HWiNFO-CPU0-Core3VID=0x2000003
; core 4 voltage (volts)
HWiNFO-CPU0-Core4VID=0x2000004
; core 5 voltage (volts)
HWiNFO-CPU0-Core5VID=0x2000005
; core 6 voltage (volts)
HWiNFO-CPU0-Core6VID=0x2000006
; core 7 voltage (volts)
HWiNFO-CPU0-Core7VID=0x2000007
; core 8 voltage (volts)
HWiNFO-CPU0-Core8VID=0x2000006
; core 9 voltage (volts)
HWiNFO-CPU0-Core9VID=0x2000007
; core 0 thermal throttling (yes/no)
HWiNFO-CPU0-Core0Tt=0x2000000
; core 1 thermal throttling (yes/no)
HWiNFO-CPU0-Core1Tt=0x2000001
; core 2 thermal throttling (yes/no)
HWiNFO-CPU0-Core2Tt=0x2000002
; core 3 thermal throttling (yes/no)
HWiNFO-CPU0-Core3Tt=0x2000003
; core 4 thermal throttling (yes/no)
HWiNFO-CPU0-Core4Tt=0x2000004
; core 5 thermal throttling (yes/no)
HWiNFO-CPU0-Core5Tt=0x2000005
; core 6 thermal throttling (yes/no)
HWiNFO-CPU0-Core6Tt=0x2000006
; core 7 thermal throttling (yes/no)
HWiNFO-CPU0-Core7Tt=0x2000007
; core 8 thermal throttling (yes/no)
HWiNFO-CPU0-Core8Tt=0x2000006
; core 9 thermal throttling (yes/no)
HWiNFO-CPU0-Core9Tt=0x2000007

;
; CPU 0 DTS
;
; sensor ID and instance
HWiNFO-CPU0-DTS-SensorId=0xf0000400
HWiNFO-CPU0-DTS-SensorInstance=0x0
; entry IDs
; core 0 temperature (degrees)
HWiNFO-CPU0-DTS-Core0Temp=0x1000000
; core 1 temperature (degrees)
HWiNFO-CPU0-DTS-Core1Temp=0x1000001
; core 2 temperature (degrees)
HWiNFO-CPU0-DTS-Core2Temp=0x1000002
; core 3 temperature (degrees)
HWiNFO-CPU0-DTS-Core3Temp=0x1000003
; core 4 temperature (degrees)
HWiNFO-CPU0-DTS-Core4Temp=0x1000004
; core 5 temperature (degrees)
HWiNFO-CPU0-DTS-Core5Temp=0x1000005
; core 6 temperature (degrees)
HWiNFO-CPU0-DTS-Core6Temp=0x1000006
; core 7 temperature (degrees)
HWiNFO-CPU0-DTS-Core7Temp=0x1000007
; core 8 temperature (degrees)
HWiNFO-CPU0-DTS-Core8Temp=0x1000008
; core 8 temperature (degrees)
HWiNFO-CPU0-DTS-Core9Temp=0x1000009

;
; Motherboard
;
; sensor ID and instance
HWiNFO-MOBO-SensorId=0xf7067910
HWiNFO-MOBO-SensorInstance=0x0
; entry IDs
; CPU fan speed (RPM)
HWiNFO-MOBO-CPUFan=0x3000001
; GPU fan speed (RPM)
HWiNFO-MOBO-GPUFan=0x0

;
; GPU 0
;
; sensor ID and instance
HWiNFO-GPU0-SensorId=0xe0002000
HWiNFO-GPU0-SensorInstance=0x0
; entry IDs
; GPU core clock frequency (MHz)
HWiNFO-GPU0-Clock=0x6000000
; GPU temperature (degrees)
HWiNFO-GPU0-Temp=0x1000000
; GPU load (percent)
HWiNFO-GPU0-CoreLoad=0x7000000
; GPU memory clock frequency (MHz)
HWiNFO-GPU0-MemoryClock=0x6000004
; GPU memory usage (percent)
HWiNFO-GPU0-MemoryUsage=0x7000008
; GPU memory allocated (MB)
HWiNFO-GPU0-MemoryAlloc=0x800003c
; GPU fan speed (RPM)
HWiNFO-GPU0-FanSpeed=0x3000000
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU0-FanUsage=0x8000000
; GPU shader clock
HWiNFO-GPU0-VideoClock=0x6000005
; GPU memory controller usage
HWiNFO-GPU0-MemController=0x7000001
; GPU core voltage (volts)
HWiNFO-GPU0-CoreVoltage=0x2000000

;
; GPU 1
;
; sensor ID and instance
HWiNFO-GPU1-SensorId=0xe0002000
HWiNFO-GPU1-SensorInstance=0x14
; entry IDs
; GPU core clock frequency (MHz)
HWiNFO-GPU1-Clock=0x6000000
; GPU temperature (degrees)
HWiNFO-GPU1-Temp=0x1000000
; GPU load (percent)
HWiNFO-GPU1-CoreLoad=0x7000000
; GPU memory clock frequency (MHz)
HWiNFO-GPU1-MemoryClock=0x6000004
; GPU memory usage (percent)
HWiNFO-GPU1-MemoryUsage=0x7000008
; GPU memory allocated (MB)
HWiNFO-GPU1-MemoryAlloc=0x800003c
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU1-FanSpeed=0x3000000
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU1-FanUsage=0x8000000
; GPU shader clock
HWiNFO-GPU1-VideoClock=0x6000005
; GPU memory controller usage
HWiNFO-GPU1-MemController=0x7000001
; GPU core voltage (volts)
HWiNFO-GPU1-CoreVoltage=0x2000000

;
; S.M.A.R.T. Drive 1
;
; disk 1
HWiNFO-SMART-Disk1-SensorId=0xf0000100
HWiNFO-SMART-Disk1-SensorInstance=0x0
HWiNFO-SMART-Disk1-Temp=0x1000001
HWiNFO-SMART-Disk1-Letter=C
; disk 2
HWiNFO-SMART-Disk2-SensorId=0xf0000100
HWiNFO-SMART-Disk2-SensorInstance=0x2
HWiNFO-SMART-Disk2-Temp=0x1000000
HWiNFO-SMART-Disk2-Letter=E
; disk 3
HWiNFO-SMART-Disk3-SensorId=0xf0000100
HWiNFO-SMART-Disk3-SensorInstance=0x1
HWiNFO-SMART-Disk3-Temp=0x1000000
HWiNFO-SMART-Disk3-Letter=D
; disk 4
HWiNFO-SMART-Disk4-SensorId=0xf0000100
HWiNFO-SMART-Disk4-SensorInstance=0x0
HWiNFO-SMART-Disk4-Temp=0x0
HWiNFO-SMART-Disk4-Letter=""
; disk 5
HWiNFO-SMART-Disk5-SensorId=0xf0000100
HWiNFO-SMART-Disk5-SensorInstance=0x0
HWiNFO-SMART-Disk5-Temp=0x0
HWiNFO-SMART-Disk5-Letter=""
; disk 6
HWiNFO-SMART-Disk6-SensorId=0xf0000100
HWiNFO-SMART-Disk6-SensorInstance=0x0
HWiNFO-SMART-Disk6-Temp=0x0
HWiNFO-SMART-Disk6-Letter=""
; disk 7
HWiNFO-SMART-Disk7-SensorId=0xf0000100
HWiNFO-SMART-Disk7-SensorInstance=0x0
HWiNFO-SMART-Disk7-Temp=0x0
HWiNFO-SMART-Disk7-Letter=""
; disk 8
HWiNFO-SMART-Disk8-SensorId=0xf0000100
HWiNFO-SMART-Disk8-SensorInstance=0x0
HWiNFO-SMART-Disk8-Temp=0x0
HWiNFO-SMART-Disk8-Letter=""
; disk 9
HWiNFO-SMART-Disk9-SensorId=0xf0000100
HWiNFO-SMART-Disk9-SensorInstance=0x0
HWiNFO-SMART-Disk9-Temp=0x0
HWiNFO-SMART-Disk9-Letter=""
; disk 10
HWiNFO-SMART-Disk10-SensorId=0xf0000100
HWiNFO-SMART-Disk10-SensorInstance=0x0
HWiNFO-SMART-Disk10-Temp=0x0
HWiNFO-SMART-Disk10-Letter=""
rowSpacing=1
