[Variables]
tempUOM=C

showGpuName=1
showMemoryClock=1
showMemoryController=1
showVideoClock=1
showCoreVoltage=1
showLineGraph=1
showTempGraph=1

gpuName=auto

useManualMaxVram=0
maxVram=3000
useMoboFanSensor=0

dualGpuMode=0

colorCoreUsage=255,246,42
colorMemoryUsage=107,198,250
colorFanUsage=107,238,98
colorMemoryController=255,204,0
colorTempGraph=200,0,0

; ====== DEFAULTS ======

dColorCoreUsage=255,246,42
dColorMemoryUsage=107,198,250
dColorFanUsage=107,238,98
dColorMemoryController=255,204,0