[Variables]
interfaceEthernet=Qualcomm Atheros AR8152 PCI-E Fast Ethernet Controller (NDIS 6.30)
interfaceWireless=Realtek RTL8188CE Wireless LAN 802.11n PCI-E NIC
interfaceOther=

censorExternalIp=0
showSpeedtestButton=1
showPing=0
showNetTotals=1
showLineGraph=1
showPeakNetworkUsage=0
monitoringType=netMonitor

pingUrl=google.com

colorUpload=107,238,98
colorDownload=255,246,42
colorPeak=99,125,217

colorGlobe=137,190,250

autoAdapterConfig=0
