[Variables]
interface=Best

interfaceEthernet=Intel(R) Ethernet Connection (2) I219-V
interfaceWireless=
interfaceOther=

trafficSuffix=B/s

censorExternalIp=0
showSpeedtestButton=1
showPing=0
showNetTotals=1
showLineGraph=1
showPeakNetworkUsage=0
useNetMonitor=1

pingUrl=google.com

autoAdapterConfig=0

colorUpload=107,238,98
colorDownload=255,246,42
colorPeak=99,125,217

; ====== DEFAULTS ======

dColorUpload=107,238,98
dColorDownload=255,246,42
dColorPeak=99,125,217
