[Variables]
showLineGraph=1
processLabelFontFace=Roboto
percentDecimals=1

processes=5
stdProcessesMode=1
processBlacklist=_Total,Idle,dwm,csrss,svchost,lsass,System,spoolsv
pinnedProcesses=

; Colors
colorProcess1=107,238,98
colorProcess2=255,246,42
colorProcess3=250,158,0
colorProcess4=236,28,70
colorProcess5=199,36,199
colorProcess6=145,70,232
colorProcess7=42,112,250
colorProcess8=43,224,224
colorProcess9=121,182,62
colorProcess10=204,255,0
colorProcess11=250,205,22
colorProcess12=191,100,55
colorProcess13=201,41,56
colorProcess14=179,0,91
colorProcess15=153,84,166
colorProcess16=99,125,217
