[Variables]
showAvgUsage=0
showBars=1
showLineGraph=0
processLabelFontFace=Roboto Cn

processes=5
processMode=1
processBlacklist=_Total|Idle|dwm|csrss|svchost|lsass|System|spoolsv

fpfProcessCpuDepth=3
fpfProcessRamDepth=3
fpfProcessGpuDepth=3
fpfProcessVramDepth=3

; Colors
colorProcess1=107,238,98
colorProcess2=255,246,42
colorProcess3=250,158,0
colorProcess4=236,28,70
colorProcess5=199,36,199
colorProcess6=145,70,232
colorProcess7=42,112,250
colorProcess8=43,224,224
colorProcess9=121,182,62
colorProcess10=204,255,0

colorCpuUsage=107,238,98
colorGpuUsage=107,238,98

dColorProcess1=107,238,98
dColorProcess2=255,246,42
dColorProcess3=250,158,0
dColorProcess4=236,28,70
dColorProcess5=199,36,199
dColorProcess6=145,70,232
dColorProcess7=42,112,250
dColorProcess8=43,224,224
dColorProcess9=121,182,62
dColorProcess10=204,255,0

dColorCpuUsage=107,238,98
dColorGpuUsage=107,238,98

; HWiNFO
HWiNFO-GPU0-CoreLoad-SensorId=0xe0002000
HWiNFO-GPU0-CoreLoad-SensorInstance=0x0
HWiNFO-GPU0-CoreLoad-EntryId=0x7000000

[HWiNFO-Config]

[HWiNFO-Config-GPU0]
HWiNFO-GPU0-CoreLoad=GPU Core Load
