[Variables]
showLineGraph=0
processLabelFontFace=Roboto
percentDecimals=1

processes=5
stdProcessesMode=1
processBlacklist=_Total|Idle|dwm|csrss|svchost|lsass|System|spoolsv|[#pProcess1]|[#pProcess2]|[#pProcess3]|[#pProcess4]|[#pProcess5]

pProcess1=factorio
pProcess2=
pProcess3=
pProcess4=
pProcess5=

showPProcess1=0
showPProcess2=0
showPProcess3=0
showPProcess4=0
showPProcess5=0

; Colors
colorPProcess1=107,238,98
colorPProcess2=255,246,42
colorPProcess3=250,158,0
colorPProcess4=236,28,70
colorPProcess5=199,36,199
