[Variables]
; - INCLUDED -
; coordinates
latitude=40.712728
longitude=-74.006015
; units: one of "e" (imperial), "m" (metric) or "h" (hybrid - celsius with miles, U.K.)
units=e
; language
language=en-US
; update rate
updateRate=600

; - OURS -

showHumidity=1
showUv=1
showUvChart=1
showAtmPressure=1
showVisibility=1
showDewpoint=1
showWindInfo=1
showSunMoonInfo=1
showMoonAngle=1

timeFormat=WinShort
customTimeFormat=%#I:%M %p
