[IncludeCoreMeasures32]
@includeCoreMeasures32=CoreMeasures32.inc

; Core Usages
[MeasureCpuUsageCore33]
Measure=CPU
Processor=33
Disabled=(#cpuCores# < 33)

[MeasureCpuUsageCore34]
Measure=CPU
Processor=34
Disabled=(#cpuCores# < 34)

[MeasureCpuUsageCore35]
Measure=CPU
Processor=35
Disabled=(#cpuCores# < 35)

[MeasureCpuUsageCore36]
Measure=CPU
Processor=36
Disabled=(#cpuCores# < 36)

[MeasureCpuUsageCore37]
Measure=CPU
Processor=37
Disabled=(#cpuCores# < 37)

[MeasureCpuUsageCore38]
Measure=CPU
Processor=38
Disabled=(#cpuCores# < 38)

[MeasureCpuUsageCore39]
Measure=CPU
Processor=39
Disabled=(#cpuCores# < 39)

[MeasureCpuUsageCore40]
Measure=CPU
Processor=40
Disabled=(#cpuCores# < 40)

[MeasureCpuUsageCore41]
Measure=CPU
Processor=41
Disabled=(#cpuCores# < 41)

[MeasureCpuUsageCore42]
Measure=CPU
Processor=42
Disabled=(#cpuCores# < 42)

[MeasureCpuUsageCore43]
Measure=CPU
Processor=43
Disabled=(#cpuCores# < 43)

[MeasureCpuUsageCore44]
Measure=CPU
Processor=44
Disabled=(#cpuCores# < 44)

[MeasureCpuUsageCore45]
Measure=CPU
Processor=45
Disabled=(#cpuCores# < 45)

[MeasureCpuUsageCore46]
Measure=CPU
Processor=46
Disabled=(#cpuCores# < 46)

[MeasureCpuUsageCore47]
Measure=CPU
Processor=47
Disabled=(#cpuCores# < 47)

[MeasureCpuUsageCore48]
Measure=CPU
Processor=48
Disabled=(#cpuCores# < 48)