[IncludeCoreMeasures48]
@includeCoreMeasures48=CoreMeasures48.inc

; Core Usages
[MeasureCpuUsageCore49]
Measure=CPU
Processor=49
Disabled=(#cpuCores# < 49)

[MeasureCpuUsageCore50]
Measure=CPU
Processor=50
Disabled=(#cpuCores# < 50)

[MeasureCpuUsageCore51]
Measure=CPU
Processor=51
Disabled=(#cpuCores# < 51)

[MeasureCpuUsageCore52]
Measure=CPU
Processor=52
Disabled=(#cpuCores# < 52)

[MeasureCpuUsageCore53]
Measure=CPU
Processor=53
Disabled=(#cpuCores# < 53)

[MeasureCpuUsageCore54]
Measure=CPU
Processor=54
Disabled=(#cpuCores# < 54)

[MeasureCpuUsageCore55]
Measure=CPU
Processor=55
Disabled=(#cpuCores# < 55)

[MeasureCpuUsageCore56]
Measure=CPU
Processor=56
Disabled=(#cpuCores# < 56)

[MeasureCpuUsageCore57]
Measure=CPU
Processor=57
Disabled=(#cpuCores# < 57)

[MeasureCpuUsageCore58]
Measure=CPU
Processor=58
Disabled=(#cpuCores# < 58)

[MeasureCpuUsageCore59]
Measure=CPU
Processor=59
Disabled=(#cpuCores# < 59)

[MeasureCpuUsageCore60]
Measure=CPU
Processor=60
Disabled=(#cpuCores# < 60)

[MeasureCpuUsageCore61]
Measure=CPU
Processor=61
Disabled=(#cpuCores# < 61)

[MeasureCpuUsageCore62]
Measure=CPU
Processor=62
Disabled=(#cpuCores# < 62)

[MeasureCpuUsageCore63]
Measure=CPU
Processor=63
Disabled=(#cpuCores# < 63)

[MeasureCpuUsageCore64]
Measure=CPU
Processor=64
Disabled=(#cpuCores# < 64)