[TitleString]
Meter=String
MeterStyle=StyleString | StyleStringCenterAlign
FontSize=17
; StringStyle=Bold
FontColor=#colorAccent#
Y=#contentMargin#
Text="Version [MeasureReleaseVersion] is now available!"
DynamicVariables=1

[UpdateButtonString]
Meter=String
MeterStyle=StyleString | StyleStringButton
X=(#contentMarginRight# - 40)
Y=15R
Text="Get the update from DeviantArt"

[UpdateButtonImage]
Meter=Image
MeterStyle=StyleStringButtonImage

[ChangelogButtonString]
Meter=String
MeterStyle=StyleString | StyleStringButton
X=(#contentMarginRight# - 40)
Y=15R
Text="View changelog"

[ChangelogButtonImage]
Meter=Image
MeterStyle=StyleStringButtonImage

[IgnoreButtonString]
Meter=String
MeterStyle=StyleString | StyleStringButton
X=(#contentMarginRight# - 40)
Y=30R
Text="Ignore..."

[IgnoreButtonImage]
Meter=Image
MeterStyle=StyleStringButtonImage
