[Variables]
; CPU Meter
autoMaxCpuTemp=100
autoMaxCpuFan=1
; Network Meter
externalIp=67.2.53.26

; - Disks Meter -

; Disk ID from index
d1=C
d2=
d3=
d4=
d5=
d6=
d7=
d8=
d9=
d10=
; Disk exists
hideDisk1=0
hideDisk2=1
hideDisk3=1
hideDisk4=1
hideDisk5=1
hideDisk6=1
hideDisk7=1
hideDisk8=1
hideDisk9=1
hideDisk10=1
; Disk Index from ID
diskAIndex=0
diskBIndex=0
diskCIndex=1
diskDIndex=0
diskEIndex=0
diskFIndex=0
diskGIndex=0
diskHIndex=0
diskIIndex=0
diskJIndex=0
diskKIndex=0
diskLIndex=0
diskMIndex=0
diskNIndex=0
diskOIndex=0
diskPIndex=0
diskQIndex=0
diskRIndex=0
diskSIndex=0
diskTIndex=0
diskUIndex=0
diskVIndex=0
diskWIndex=0
diskXIndex=0
diskYIndex=0
diskZIndex=0
; Show element (Temperature / Eject Button)
showDiskAElement=1
showDiskBElement=1
showDiskCElement=1
showDiskDElement=1
showDiskEElement=1
showDiskFElement=1
showDiskGElement=1
showDiskHElement=1
showDiskIElement=1
showDiskJElement=1
showDiskKElement=1
showDiskLElement=1
showDiskMElement=1
showDiskNElement=1
showDiskOElement=1
showDiskPElement=1
showDiskQElement=1
showDiskRElement=1
showDiskSElement=1
showDiskTElement=1
showDiskUElement=1
showDiskVElement=1
showDiskWElement=1
showDiskXElement=1
showDiskYElement=1
showDiskZElement=1
; Other (dummy variables, hidden disks list)
d0=
hideDisk0=1
oobDisks=
showDiskElement=1
