[ReleaseVersions]
stable=1.2.3
dev=1.3.0-rc.1

[Changelogs]
stableChangelog=v1.2.2 - 2017-8-3[#CRLF]- ACTUALLY fixed core temperature issues[#CRLF]- Changed all author references to raiguard
devChangelog=v1.3.0-rc.1 - 2018-1-21[#CRLF]- Added core voltages to CPU meter[#CRLF]- Fixed dual GPU meter settings[#CRLF]- Fixed issue with large row spacing in Disks Meter

[URLs]
stableUrl=https://github.com/raiguard/ModernGadgets/releases/download/v1.2.3/ModernGadgets_1.2.3.rmskin
devUrl=https://github.com/raiguard/ModernGadgets/releases/download/v1.3.0-rc.1/ModernGadgets_1.3.0-rc.1.rmskin