; MODERNGADGETS GLOBAL SETTINGS

[Variables]

lineGraphAa=0

; ----- HWiNFO -----

;
; CPU 0
;
; sensor ID and instance
HWiNFO-CPU0-SensorId=0xf0000300
HWiNFO-CPU0-SensorInstance=0x0
; entry IDs
; CPU usage (percent)
HWiNFO-CPU0-Usage=0x7000009
; core 0 clock frequency (MHz)
HWiNFO-CPU0-Core0Clock=0x6000000
; core 1 clock frequency (MHz)
HWiNFO-CPU0-Core1Clock=0x6000001
; core 2 clock frequency (MHz)
HWiNFO-CPU0-Core2Clock=0x6000002
; core 3 clock frequency (MHz)
HWiNFO-CPU0-Core3Clock=0x6000003
; core 4 clock frequency (MHz)
HWiNFO-CPU0-Core4Clock=0x6000004
; core 5 clock frequency (MHz)
HWiNFO-CPU0-Core5Clock=0x6000005
; core 6 clock frequency (MHz)
HWiNFO-CPU0-Core6Clock=0x6000006
; core 7 clock frequency (MHz)
HWiNFO-CPU0-Core7Clock=0x6000007
; core 0 voltage (volts)
HWiNFO-CPU0-Core0VID=0x2000000
; core 1 voltage (volts)
HWiNFO-CPU0-Core1VID=0x2000001
; core 2 voltage (volts)
HWiNFO-CPU0-Core2VID=0x2000002
; core 3 voltage (volts)
HWiNFO-CPU0-Core3VID=0x2000003
; core 4 voltage (volts)
HWiNFO-CPU0-Core4VID=0x2000004
; core 5 voltage (volts)
HWiNFO-CPU0-Core5VID=0x2000005
; core 6 voltage (volts)
HWiNFO-CPU0-Core6VID=0x2000006
; core 7 voltage (volts)
HWiNFO-CPU0-Core7VID=0x2000007
; core 0 thermal throttling (yes/no)
HWiNFO-CPU0-Core0Tt=0x2000000
; core 1 thermal throttling (yes/no)
HWiNFO-CPU0-Core1Tt=0x2000001
; core 2 thermal throttling (yes/no)
HWiNFO-CPU0-Core2Tt=0x2000002
; core 3 thermal throttling (yes/no)
HWiNFO-CPU0-Core3Tt=0x2000003
; core 4 thermal throttling (yes/no)
HWiNFO-CPU0-Core4Tt=0x2000004
; core 5 thermal throttling (yes/no)
HWiNFO-CPU0-Core5Tt=0x2000005
; core 6 thermal throttling (yes/no)
HWiNFO-CPU0-Core6Tt=0x2000006
; core 7 thermal throttling (yes/no)
HWiNFO-CPU0-Core7Tt=0x2000007

;
; CPU 0 DTS
;
; sensor ID and instance
HWiNFO-CPU0-DTS-SensorId=0xf0000400
HWiNFO-CPU0-DTS-SensorInstance=0x0
; entry IDs
; core 0 temperature (degrees)
HWiNFO-CPU0-DTS-Core0Temp=0x1000000
; core 1 temperature (degrees)
HWiNFO-CPU0-DTS-Core1Temp=0x1000001
; core 2 temperature (degrees)
HWiNFO-CPU0-DTS-Core2Temp=0x1000002
; core 3 temperature (degrees)
HWiNFO-CPU0-DTS-Core3Temp=0x1000003
; core 4 temperature (degrees)
HWiNFO-CPU0-DTS-Core4Temp=0x1000004
; core 5 temperature (degrees)
HWiNFO-CPU0-DTS-Core5Temp=0x1000005
; core 6 temperature (degrees)
HWiNFO-CPU0-DTS-Core6Temp=0x1000006
; core 7 temperature (degrees)
HWiNFO-CPU0-DTS-Core7Temp=0x1000007
; maximum current core temperature (degrees)
HWiNFO-CPU0-DTS-CoreMax=0x100007f

;
; Motherboard
;
; sensor ID and instance
HWiNFO-MOBO-SensorId=0xf7067910
HWiNFO-MOBO-SensorInstance=0x0
; entry IDs
; CPU fan speed (RPM)
HWiNFO-MOBO-CPUFan=0x3000001

;
; GPU 0
;
; sensor ID and instance
HWiNFO-GPU0-SensorId=0xe0002000
HWiNFO-GPU0-SensorInstance=0x0
; entry IDs
; GPU core clock frequency (MHz)
HWiNFO-GPU0-Clock=0x6000000
; GPU temperature (degrees)
HWiNFO-GPU0-Temp=0x1000000
; GPU load (percent)
HWiNFO-GPU0-CoreLoad=0x7000000
; GPU memory clock frequency (MHz)
HWiNFO-GPU0-MemoryClock=0x6000004
; GPU memory usage (percent)
HWiNFO-GPU0-MemoryUsage=0x7000008
; GPU memory allocated (MB)
HWiNFO-GPU0-MemoryAlloc=0x800003c
; GPU fan speed (RPM)
HWiNFO-GPU0-FanSpeed=0x3000000
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU0-FanUsage=0x8000000
; GPU shader clock
HWiNFO-GPU0-VideoClock=0x6000005
; GPU memory controller usage
HWiNFO-GPU0-MemController=0x7000001
; GPU core voltage (volts)
HWiNFO-GPU0-CoreVoltage=0x2000000

;
; GPU 1
;
; sensor ID and instance
HWiNFO-GPU1-SensorId=0xe0002000
HWiNFO-GPU1-SensorInstance=0x14
; entry IDs
; GPU core clock frequency (MHz)
HWiNFO-GPU1-Clock=0x6000000
; GPU temperature (degrees)
HWiNFO-GPU1-Temp=0x1000000
; GPU load (percent)
HWiNFO-GPU1-CoreLoad=0x7000000
; GPU memory clock frequency (MHz)
HWiNFO-GPU1-MemoryClock=0x6000004
; GPU memory usage (percent)
HWiNFO-GPU1-MemoryUsage=0x7000008
; GPU memory allocated (MB)
HWiNFO-GPU1-MemoryAlloc=0x800003c
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU1-FanSpeed=0x3000000
; GPU fan usage (percent, not RPM!)
HWiNFO-GPU1-FanUsage=0x8000000
; GPU shader clock
HWiNFO-GPU1-VideoClock=0x6000005
; GPU memory controller usage
HWiNFO-GPU1-MemController=0x7000001
; GPU core voltage (volts)
HWiNFO-GPU1-CoreVoltage=0x2000000

;
; S.M.A.R.T. Drive 1
;
; disk C
HWiNFO-SMART-DiskC-SensorId=0xf0000100
HWiNFO-SMART-DiskC-SensorInstance=0x0
HWiNFO-SMART-DiskC-Temp=0x1000001
; disk D
HWiNFO-SMART-DiskD-SensorId=0xf0000100
HWiNFO-SMART-DiskD-SensorInstance=0x2
HWiNFO-SMART-DiskD-Temp=0x1000000
; disk E
HWiNFO-SMART-DiskE-SensorId=0xf0000100
HWiNFO-SMART-DiskE-SensorInstance=0x1
HWiNFO-SMART-DiskE-Temp=0x1000000
; disk F
HWiNFO-SMART-DiskF-SensorId=0
HWiNFO-SMART-DiskF-SensorInstance=0
HWiNFO-SMART-DiskF-Temp=0
; disk G
HWiNFO-SMART-DiskG-SensorId=0
HWiNFO-SMART-DiskG-SensorInstance=0
HWiNFO-SMART-DiskG-Temp=0
; disk H
HWiNFO-SMART-DiskH-SensorId=0
HWiNFO-SMART-DiskH-SensorInstance=0
HWiNFO-SMART-DiskH-Temp=0
; disk I
HWiNFO-SMART-DiskI-SensorId=0
HWiNFO-SMART-DiskI-SensorInstance=0
HWiNFO-SMART-DiskI-Temp=0
; disk J
HWiNFO-SMART-DiskJ-SensorId=0
HWiNFO-SMART-DiskJ-SensorInstance=0
HWiNFO-SMART-DiskJ-Temp=0
; disk K
HWiNFO-SMART-DiskK-SensorId=0
HWiNFO-SMART-DiskK-SensorInstance=0
HWiNFO-SMART-DiskK-Temp=0
; disk L
HWiNFO-SMART-DiskL-SensorId=0
HWiNFO-SMART-DiskL-SensorInstance=0
HWiNFO-SMART-DiskL-Temp=0
