[ReleaseVersions]
stable=1.3.1
dev=1.4.0-beta.2

[Changelogs]
stableChangelog=v1.3.1 - 2018-5-2[#CRLF]- Fixed development testing opt-in not working
devChangelog=v1.4.0-beta.2 - 2018-5-13[#CRLF]- Added Process Meter[#CRLF]- Refactored input box visuals[#CRLF]- Removed condensed font toggle for Network traffic[#CRLF]- Disk eject buttons will auto-hide if the user is not an administrator[#CRLF]- Changelog button now shows local changelog rather than the one from GitHub

[URLs]
stableUrl=https://github.com/raiguard/ModernGadgets/releases/download/v1.3.1/ModernGadgets_1.3.1.rmskin
devUrl=https://github.com/raiguard/ModernGadgets/releases/download/v1.4.0-beta.1-fix/ModernGadgets_1.4.0-beta.1.rmskin