[Variables]
fpfReadDepth=4
fpfWriteDepth=4
fpfSpaceUsedDepth=5
fpfSpaceTotalDepth=5

diskCommand="C:\Windows\explorer.exe" /E,{drive}\
histogramA=50

showDiskTemps=1
showLineGraph=1

tempUOM=C

;
; These values do not directly correspond with the drives letters defined above
;
colorDisk1=107,238,98,240
colorDisk2=255,246,42,240
colorDisk3=250,158,0,240
colorDisk4=236,28,70,240
colorDisk5=199,36,199,240
colorDisk6=145,70,232,240
colorDisk7=42,112,250,240
colorDisk8=43,224,224,240
colorDisk9=121,182,62,240
colorDisk10=204,255,0,240

colorDiskA=
colorDiskB=
colorDiskC=
colorDiskD=
colorDiskE=
colorDiskF=
colorDiskG=
colorDiskH=
colorDiskI=
colorDiskJ=
colorDiskK=
colorDiskL=
colorDiskM=
colorDiskN=
colorDiskO=
colorDiskP=
colorDiskQ=
colorDiskR=
colorDiskS=
colorDiskT=
colorDiskU=
colorDiskV=
colorDiskW=
colorDiskX=
colorDiskY=
colorDiskZ=
